#ifndef BRANCH_AND_BOUND_APP_H
#define BRANCH_AND_BOUND_APP_H

#define LINEAR_ENUM_BRANCHING 0
#define RANDOM_BRANCHING 1
#define TRUNCATION_BRANCHING 2
#define NO_LOGGING 0
#define PARTIAL_LOGGING 1
#define FULL_LOGGING 2

#endif
