---
 title: 'Literature Review: Implicit enumeration with dual bounds from approximations'
 author: Nelson Frew
 output: pdf_document
 bibliography: literature_review.bib
---


Discrete Optimisation (CITE ME) is a branch of mathematical optimisation which is concerned particularly with problems with variables constrained to take discrete values. Such problems arise when modelling discrete decision making and other logistics problems. This encompasses Mixed-Integer Programming (MIP),(CITE ME)  where some or all of the variables must be integers subject to linear constraints. MIP is of particular practical use as it can closely model real-world problems such as supply chain problems, portfolio management, scheduling problems, and numerous power production optimisation problems. The current state of the art method for finding solutions to MIP problems is the Branch-and-Bound (B&B) framework, initially described by \cite{Land} with early developments in the following years in \cite{Dakin}. B&B's strategy resolves around partially enumerating solutions to the original problem, finding bounds on the optimal value, and pruning solution branches which cannot possibly yield an optimal solution according to these bounds. For a detailed treatment, the reader is directed to \cite{Conforti}. Bounds that are used to prune solution branches for the original problem are known as *dual bounds*, and as a result, the performance of the algorithm can be highly sensitive to the quality of the bounds obtained. Other parameters, such as branching, searching, and pruning strategies all have important roles to play in a B&B's efficiency [put a final tie in here].

Intuitively, the relaxation of the original integer programming problem is simpler to solve than the original problem, however there are several ways of relaxation a given integer program  solving the Semidefinite Programming (SDP), Lagrangian, or Linear Programming (LP) relaxations. SDPs optimise objective functions with the particular constraint that the matrix being optimised is to be *positive semidefinite*, (see \cite{Vandenberghe}, \cite{Alizadeh} for details). Lovasz and Schrijver \cite{Lovasz} presented an SDP relaxation method that could target Integer Programming (IP) specifically. Finding a *Lagrangian* relaxation, as described by (CITE ME) involves removing a hard constraint of the original problem, then optimising over a variable which penalises the objective value for violations of the constraint, rather than naming such a solution infeasible. LP relaxations, introduced by (CITE ME), finally, are obtained by simply removing the integrality constraint on the original IP formulation, and solving the resultant LP problem. As mentioned, we are interested in relaxations because they provide us a way to prune our search space down in a B&B. However, as is the case with optimisation problems, the performance of methods can be highly problem specific (CITE ME). For example, (CITE ME) showed that LP relaxations are often poor in Vertex Cover, indicating that in some instances, relaxations may offer arbitrarily poor quality bounds within a B&B setting. 

Following the rise of Approximations research in the 1970s, Wolsey (1980) \cite{Wolsey} posited a means of leveraging approximation algorithm guaranteesm, weaving them into guarantees in terms of LP relaxations, and provided a means of constructed a B&B predicated on these assets. Despite being at the intersection of two fields which both derive algorithms for hard problems, such work had not been done prior. Providing a general procedure for analysing approximation algorithms, Wolsey specifies an invariant inequality between the approximated value that is maintained while optimality is not reached. Further, Wolsey demonstrates the sensitivity of such an approach to problem type by showing how failure can occur without appropriate enumeration procedures and a lower/upper bound relationship valid for incremental values per node.

Within this context we situate our work building on the ideas provided by Wolsey (1980), and in response to the limitations of current relaxation techniques, by leveraging approximation algorithm guarantees, to create implicit enumeration from *a posteriori* dual bounds.



\bibliography{literature_review}
\bibliographystyle{plain} 

