# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nelson/Documents/branch_and_bound/knapsack_dp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nelson/Documents/branch_and_bound/knapsack_dp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nelson/Documents/branch_and_bound/knapsack_dp/CMakeFiles /home/nelson/Documents/branch_and_bound/knapsack_dp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nelson/Documents/branch_and_bound/knapsack_dp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named runTests

# Build rule for target.
runTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runTests
.PHONY : runTests

# fast build rule for target.
runTests/fast:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/build
.PHONY : runTests/fast

branch_and_bound.o: branch_and_bound.c.o

.PHONY : branch_and_bound.o

# target to build an object file
branch_and_bound.c.o:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/branch_and_bound.c.o
.PHONY : branch_and_bound.c.o

branch_and_bound.i: branch_and_bound.c.i

.PHONY : branch_and_bound.i

# target to preprocess a source file
branch_and_bound.c.i:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/branch_and_bound.c.i
.PHONY : branch_and_bound.c.i

branch_and_bound.s: branch_and_bound.c.s

.PHONY : branch_and_bound.s

# target to generate assembly for a file
branch_and_bound.c.s:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/branch_and_bound.c.s
.PHONY : branch_and_bound.c.s

branch_and_bound_short_correctness_test.o: branch_and_bound_short_correctness_test.cpp.o

.PHONY : branch_and_bound_short_correctness_test.o

# target to build an object file
branch_and_bound_short_correctness_test.cpp.o:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/branch_and_bound_short_correctness_test.cpp.o
.PHONY : branch_and_bound_short_correctness_test.cpp.o

branch_and_bound_short_correctness_test.i: branch_and_bound_short_correctness_test.cpp.i

.PHONY : branch_and_bound_short_correctness_test.i

# target to preprocess a source file
branch_and_bound_short_correctness_test.cpp.i:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/branch_and_bound_short_correctness_test.cpp.i
.PHONY : branch_and_bound_short_correctness_test.cpp.i

branch_and_bound_short_correctness_test.s: branch_and_bound_short_correctness_test.cpp.s

.PHONY : branch_and_bound_short_correctness_test.s

# target to generate assembly for a file
branch_and_bound_short_correctness_test.cpp.s:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/branch_and_bound_short_correctness_test.cpp.s
.PHONY : branch_and_bound_short_correctness_test.cpp.s

fptas.o: fptas.c.o

.PHONY : fptas.o

# target to build an object file
fptas.c.o:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/fptas.c.o
.PHONY : fptas.c.o

fptas.i: fptas.c.i

.PHONY : fptas.i

# target to preprocess a source file
fptas.c.i:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/fptas.c.i
.PHONY : fptas.c.i

fptas.s: fptas.c.s

.PHONY : fptas.s

# target to generate assembly for a file
fptas.c.s:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/fptas.c.s
.PHONY : fptas.c.s

pisinger_reader.o: pisinger_reader.c.o

.PHONY : pisinger_reader.o

# target to build an object file
pisinger_reader.c.o:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/pisinger_reader.c.o
.PHONY : pisinger_reader.c.o

pisinger_reader.i: pisinger_reader.c.i

.PHONY : pisinger_reader.i

# target to preprocess a source file
pisinger_reader.c.i:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/pisinger_reader.c.i
.PHONY : pisinger_reader.c.i

pisinger_reader.s: pisinger_reader.c.s

.PHONY : pisinger_reader.s

# target to generate assembly for a file
pisinger_reader.c.s:
	$(MAKE) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/pisinger_reader.c.s
.PHONY : pisinger_reader.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... runTests"
	@echo "... branch_and_bound.o"
	@echo "... branch_and_bound.i"
	@echo "... branch_and_bound.s"
	@echo "... branch_and_bound_short_correctness_test.o"
	@echo "... branch_and_bound_short_correctness_test.i"
	@echo "... branch_and_bound_short_correctness_test.s"
	@echo "... fptas.o"
	@echo "... fptas.i"
	@echo "... fptas.s"
	@echo "... pisinger_reader.o"
	@echo "... pisinger_reader.i"
	@echo "... pisinger_reader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

