branch_and_bound_app : branch_and_bound_app.o branch_and_bound_v2.o fptas_v2.o pisinger_reader.o
	gcc branch_and_bound_app.o branch_and_bound_v2.o fptas_v2.o pisinger_reader.o -g -o branch_and_bound_app -lm

branch_and_bound_app.o : branch_and_bound_app.c
	gcc -c branch_and_bound_app.c -g -lm 

branch_and_bound_v2.o : branch_and_bound_v2.c
	gcc -c branch_and_bound_v2.c -g -lm

fptas_v2.o : fptas_v2.c
	gcc -c fptas_v2.c -g -lm

pisinger_reader.o : pisinger_reader.c
	gcc -c pisinger_reader.c -g -lm

clean :
	rm branch_and_bound_app branch_and_bound_app.o branch_and_bound_v2.o fptas_v2.o pisinger_reader.o 
